imageboard/urls.py
from django.urls import path

from . import views

app_name = 'imageboard'
urlpatterns = [
    path('<str:board_name>/', views.board_view, name='board_view'),
    path('<str:board_name>/thread/<int:post_num>', views.thread_view, name='thread_view')
]

imageboard_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imageboard.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageboard/models.py
from django.db import models

class Board(models.Model):
    name = models.CharField(max_length=32)
    short_name = models.CharField(max_length=4)

class Post(models.Model):
    name = models.CharField(max_length=32)
    subject = models.CharField(max_length=64, blank=True, null=True)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    image_name = models.CharField(max_length=64, blank=True, null=True)
    thumbnail = models.ImageField(upload_to='images', blank=True, null=True)
    text = models.CharField(max_length=2048)
    post_num = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_op = models.BooleanField()
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    thread = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    bump_order = models.IntegerField(blank=True, null=True)

imageboard/forms.py
from django import forms

class OpPostForm(forms.Form):
    subject = forms.CharField(label='Subject', max_length=20, required=False)
    name = forms.CharField(label='Name', max_length=20, required=False)
    text = forms.CharField(label='Post', max_length=2000)
    image = forms.ImageField()

class PostForm(forms.Form):
    name = forms.CharField(label='Name', max_length=20, required=False)
    text = forms.CharField(label='Post', max_length=2000, required=False)
    image = forms.ImageField(required=False)

    # to allow text OR an image
    def clean(self):
        clean_data = super().clean()
        if not (clean_data.get('text') is not None or clean_data.get(image) is not None):
            raise ValidationError("Post requires text or an image.")
        return clean_data

imageboard/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Board, Post
from .forms import OpPostForm, PostForm

import os
from PIL import Image

def board_view(request, board_name):
    board = Board.objects.get(short_name=board_name)
    all_boards = Board.objects.all()

    if request.method == 'POST':
        if OpPostForm(request.POST, request.FILES).is_valid():
            op_post = Post(
                name = request.POST.get('name'),
                subject = request.POST.get('subject'),
                image = request.FILES['image'],
                text = request.POST.get('text'),
                post_num = Post.objects.filter(board=board).count() + 1,
                is_op = True,
                board = board,
                thread = None,
                bump_order = 0
            )

            # Set the name to anonymous if none was given
            if op_post.name == '' or op_post.name is None:
                op_post.name = 'Anonymous'

            # Process image
            op_post.image_name = op_post.image.name
            thumb = Image.open(op_post.image)
            thumb.thumbnail((250, 250))
            thumb_path = os.path.splitext(op_post.image.path)[0] + 's.jpg'
            thumb.save(thumb_path, 'JPEG')
            op_post.thumbnail.name = thumb_path
            op_post.save()

            return render(request, 'thread.html', {
                'boards': all_boards,
                'board': board,
                'op_post': op_post,
                'posts': []
            })
        else:
            print(OpPostForm(request.POST).errors)

    else: # GET
        op_posts = list(Post.objects.filter(board=board, is_op=True).order_by('bump_order'))
        op_posts = op_posts[:10] # Get the last 10 bumped threads
        for i in op_posts:
            i.replies = list(Post.objects.filter(thread=i).order_by('post_num'))
            i.replies = i.replies[:5] # Get the latest 5 replies to those threads
        return render(request, 'board.html', {
            'boards': all_boards,
            'board': board,
            'op_posts': op_posts
        })

def thread_view(request, board_name, post_num):
    all_boards = Board.objects.all()
    board = Board.objects.get(short_name=board_name)
    op_post = Post.objects.get(board=board, post_num=post_num)

    if request.method == 'POST':
        if PostForm(request.POST, request.FILES).is_valid():
            post = Post(
                name = request.POST.get('name'),
                image = request.FILES['image'] if 'image' in request.FILES else None,
                text = request.POST.get('text'),
                post_num = Post.objects.filter(board=board).count() + 1,
                is_op = False,
                board = board,
                thread = op_post
            )

            # Set the name to anonymous if none was given
            if post.name == '' or post.name is None:
                post.name = 'Anonymous'

            # Process image
            if post.image:
                post.image_name = post.image.name
                thumb = Image.open(post.image)
                thumb.thumbnail((250, 250))
                thumb_path = os.path.splitext(post.image.path)[0] + 's.jpg'
                thumb.save(thumb_path, 'JPEG')
                post.thumbnail.name = thumb_path

            post.save()
        else:
            print(PostForm(request.POST, request.FILES).errors)

    posts = list(Post.objects.filter(thread=op_post).order_by('post_num'))
    return render(request, 'thread.html', {
        'boards': all_boards,
        'board': board,
        'op_post': op_post,
        'posts': posts
    })

imageboard/templates/board.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>/{{ board.short_name }}/ - {{ board.name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'imageboard/style.css' %}">
</head>
<body>
    <div id="board_nav">
        <span class="board_list">
            [
            {% for b in boards %}
            <a href="{% url 'imageboard:board_view' b.short_name %}" title="{{ b.name }}">{{ b.short_name }}</a>
            {% if forloop.counter < boards|length %}
            /
            {% endif %}
            {% endfor %}
            ]
    </div>

    <div id="board_title">/{{ board.short_name }}/ - {{ board.name }}</div>

    <hr>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table id="thread_table" style="display: table;">
            <tbody>
                <tr data-type="Name">
                    <td>Name</td>
                    <td><input name="name" type="text" placeholder="Anonymous"></td>
                </tr>
                <tr data-type="Subject">
                    <td>Subject</td>
                    <td><input name="subject" type="text"></td>
                </tr>
                <tr data-type="Text">
                    <td>Post</td>
                    <td><textarea name="text" cols="48" rows="4" wrap="soft"></textarea></td>
                    <td><input type="submit" value="Post"></td>
                </tr>
                <tr data-type="Image">
                    <td>Image</td>
                    <td><input name="image" type="file"></td>
                </tr>
            </tbody>
        </table>
    </form>

    <hr>

    {% for op_post in op_posts %}
    <div class="op_post">
        <div class="op_post_info">
            <span class="subject">{{ op_post.subject }}</span>
            <span class="name">{{ op_post.name }}</span>
            <span class="timestamp">{{ op_post.timestamp }}</span>
            <span class="post_num">No. {{ op_post.post_num }}</span>
            <span class="thread_link"> [<a href="{% url 'imageboard:thread_view' board.short_name op_post.post_num %}">Open Thread</a>]</span>
        </div>
        <div class="op_post_image">
            <a href="{{ op_post.image.url }}"><img src="{{ op_post.thumbnail.url }}"></a>
        </div>
        <p class="text">{% autoescape on %}{{ op_post.text | linebreaksbr }}{% endautoescape %}</p>

        {% for post in op_post.replies %}
        <div class="post">

            <div class="post_info">
                <span class="name">{{ post.name }}</span>
                <span class="timestamp">{{ post.timestamp }}</span>
                <span class="post_num">No. {{ post.post_num }}</span>
            </div>
            {% if post.image %}
            <div class="post_image">
                <a href="{{ post.image.url }}"><img src="{{ post.thumbnail.url }}"></a>
            </div>
            {% endif %}
            <p class="text">{% autoescape on %}{{ post.text | linebreaksbr }}{% endautoescape %}</p>
        </div>
        {% endfor %}
        <hr>
    </div>
    {% endfor %}
</body>
</html>

imageboard/templates/thread.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>/{{ board.short_name }}/ - {{ op_post.subject }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'imageboard/style.css' %}">
</head>
<body>
    <div id="board_nav">
        <span class="board_list">
            [
            {% for b in boards %}
            <a href="{% url 'imageboard:board_view' b.short_name %}" title="{{ b.name }}">{{ b.short_name }}</a>
            {% if forloop.counter < boards|length %}
            /
            {% endif %}
            {% endfor %}
            ]
    </div>

    <div id="board_title">/{{ board.short_name }}/ - {{ board.name }}</div>

    <hr>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table id="post_table" style="display: table;">
            <tbody>
                <tr data-type="Name">
                    <td>Name</td>
                    <td><input name="name" type="text" placeholder="Anonymous"></td>
                </tr>
                <tr data-type="Text">
                    <td>Post</td>
                    <td><textarea name="text" cols="48" rows="4" wrap="soft"></textarea></td>
                    <td><input type="submit" value="Post"></td>
                </tr>
                <tr data-type="Image">
                    <td>Image</td>
                    <td><input name="image" type="file"></td>
                </tr>
            </tbody>
        </table>
    </form>

    <hr>

    <div class="op_post">
        <div class="op_post_info">
            <span class="subject">{{ op_post.subject }}</span>
            <span class="name">{{ op_post.name }}</span>
            <span class="timestamp">{{ op_post.timestamp }}</span>
            <span class="post_num">No. {{ op_post.post_num }}</span>
        </div>
        <div class="op_post_image">
            <a href="{{ op_post.image.url }}"><img src="{{ op_post.thumbnail.url }}"></a>
        </div>
        <p class="text">{% autoescape on %}{{ op_post.text | linebreaksbr }}{% endautoescape %}</p>
    </div>

    {% for post in posts %}
    <div class="post">
        <div class="post_info">
            <span class="name">{{ post.name }}</span>
            <span class="timestamp">{{ post.timestamp }}</span>
            <span class="post_num">No. {{ post.post_num }}</span>
        </div>
        {% if post.image %}
        <div class="post_image">
            <a href="{{ post.image.url }}"><img src="{{ post.thumbnail.url }}"></a>
        </div>
        {% endif %}
        <p class="text">{% autoescape on %}{{ post.text | linebreaksbr }}{% endautoescape %}</p>
    </div>
    {% endfor %}
    <hr>
</body>
</html>